// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabAmI3m_FR8a53EiSEQrU-dBffR8IsLk',
    appId: '1:782499659196:web:55385579d9d0b15d8e7fb9',
    messagingSenderId: '782499659196',
    projectId: 'bateacher',
    authDomain: 'bateacher.firebaseapp.com',
    storageBucket: 'bateacher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLpfl7riao0zfN34AhBJuzJnm5aFK3e8',
    appId: '1:782499659196:android:8b87e92086e27f788e7fb9',
    messagingSenderId: '782499659196',
    projectId: 'bateacher',
    storageBucket: 'bateacher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtDCJB3wqptmqqBoEKWHjN9hMwgH7HKGY',
    appId: '1:782499659196:ios:43e8f284f09b7f1d8e7fb9',
    messagingSenderId: '782499659196',
    projectId: 'bateacher',
    storageBucket: 'bateacher.appspot.com',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtDCJB3wqptmqqBoEKWHjN9hMwgH7HKGY',
    appId: '1:782499659196:ios:f78f80c0f8afce1f8e7fb9',
    messagingSenderId: '782499659196',
    projectId: 'bateacher',
    storageBucket: 'bateacher.appspot.com',
    iosBundleId: 'com.example.studentApp.RunnerTests',
  );
}
